version: "3.8"

services:
  # Ollama Translator Web Application
  ollama-translator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DEFAULT_API_URL=http://ollama:11434
      - NEXT_PUBLIC_DEFAULT_MODEL=llama3.1
      - NEXT_PUBLIC_DEFAULT_CONFIG_ID=ollama-default
      # Uncomment and configure custom LLM if needed
      # - NEXT_PUBLIC_CUSTOM_LLM_NAME=Custom LLM
      # - NEXT_PUBLIC_CUSTOM_API_URL=http://custom-llm:8080
      # - NEXT_PUBLIC_CUSTOM_MODEL=custom-model
      # - NEXT_PUBLIC_CUSTOM_API_KEY=your_api_key
    depends_on:
      - ollama
    networks:
      - translator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ollama Service (Optional - for local LLM inference)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - translator-network
    restart: unless-stopped
    # Uncomment the following lines if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ollama-translator
    networks:
      - translator-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  ollama-data:

networks:
  translator-network:
    driver: bridge
